const CACHE = 'cache-only-v1';

// При установке воркера мы должны закешировать часть данных (статику).
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open('v1').then((cache) => {
      return cache.addAll([
        '/',
				'index.html',
				'/extensions/ext-shapes.xml',
				'/images/mappoint.gif',
				'/images/AlphaBar.png',
				'/images/bar-opacity.png',
				'/images/Bars.png',
				'/images/drag.png',
				'/images/dragging.png',
				'/images/eyedropper.png',
				'/images/logo.png',
				'/images/map-opacity.png',
				'/images/mappoint_c.png',
				'/images/mappoint_f.png',
				'/images/Maps.png',
				'/images/pencil_cursor.png',
				'/images/preview-opacity.png',
				'/images/rotate.png',
				'/images/eyedropper.svg',
				'/images/favicon.svg',
				'/images/NoColor.svg',
				'/images/placeholder.svg',
				'/images/rangearrows.svg',
				'/images/rangearrows2.svg',

				'/css/base.css',
				'/css/method-draw.css',
				'/css/jpicker.css',
				'/css/jgraduate.css',
				'/css/fonts.css',
				'/css/dropdown.css',
				'/css/draginput.css',
				'/css/menu.css',
				'/css/rulers.css',
				'/css/palette.css',
				'/css/color-tool.css',
				'/css/context-menu.css',
				'/css/shapelib.css',
				'/css/modal.css',
				'/css/source.css',
				'/css/keyboard.css',
				'/css/dialog.css',
				'/css/app.css',
				'/css/tools.css',
				'/css/button.css',
				'/css/select.css',
				'/css/panel.css',
				'/css/align_buttons.css',
				'/css/text.css',
				'/css/sponsors.css',
				'/css/zoom-dropdown.css',
				'/css/loading.css',


				'/js/loading.js',
				'/js/lib/jquery-3.5.1.min.js',
				'/js/lib/pathseg.js',
				'/js/lib/jquery.hotkeys.min.js',
				'/js/lib/jquery.jgraduate.js',
				'/js/lib/jquery.contextMenu.js',
				'/js/lib/jquery-ui-1.8.17.custom.min.js',
				'/js/jquery.attr.js',
				'/js/lib/jquery-draginput.js',
				'/js/lib/css.min.js',
				'/js/utils.js',
				'/js/dao.js',
				'/js/state.js',
				'/js/browser.js',
				'/js/svgutils.js',
				'/js/history.js',
				'/js/select.js',
				'/js/path.js',
				'/js/sanitize.js',
				'/js/units.js',
				'/js/math.js',
				'/js/translate.js',
				'/js/svgtransformlist.js',
				'/js/draw.js',
				'/js/svgcanvas.js',
				'/js/editor.js',
				'/js/Canvas.js',
				'/js/Text.js',
				'/js/Pan.js',
				'/js/Panel.js',
				'/js/Rulers.js',
				'/js/Toolbar.js',
				'/js/Menu.js',
				'/js/Keyboard.js',
				'/js/Import.js',
				'/js/PaintBox.js',
				'/js/Palette.js',
				'/js/Zoom.js',
				'/js/Modal.js',
				'/js/Title.js',
				'/js/Darkmode.js',
				'/js/ContextMenu.js',
				'/js/Shapelib.js',
				'/js/fonts.js',
				'/js/dialog.js',
				'/js/lib/contextmenu.js',
				'/js/lib/jpicker.min.js',
				'/js/lib/mousewheel.js',
				'/js/eyedropper.js',
				'/js/lib/requestanimationframe.js',
				'/js/lib/taphold.js',
				'/js/lib/filesaver.js',
				'/js/paste.js',
				'/js/modals.js',
				'/js/start.js',

      ]);
    })
  );
});

self.addEventListener('activate', (event) => {
	console.log('Активирован');
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request)
  );
});